/*
 * Created on 2022-04-12 ( Time 14:44:06 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;
import java.util.Date;

public class DmsDocumentM implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private BigDecimal id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private BigDecimal systemId;

    @NotNull
    @Size( min = 1, max = 100 )
    private String productName;

    @NotNull
    @Size( min = 1, max = 100 )
    private String docName;

    @Size( max = 255 )
    private String docDescription;

    @NotNull
    @Size( min = 1, max = 255 )
    private String createdBy;

    @NotNull
    private Date createdOn;

    @NotNull
    @Size( min = 1, max = 255 )
    private String modifiedBy;

    @NotNull
    private Date modifiedOn;

    @Size( max = 100 )
    private String field1;

    @Size( max = 100 )
    private String field2;

    @Size( max = 100 )
    private String field3;

    @Size( max = 100 )
    private String field4;

    @Size( max = 100 )
    private String field5;

    @Size( max = 100 )
    private String field6;

    @Size( max = 100 )
    private String field7;

    @Size( max = 100 )
    private String field8;

    @Size( max = 100 )
    private String field9;

    @Size( max = 100 )
    private String field10;

    @Size( max = 100 )
    private String field11;

    @Size( max = 100 )
    private String field12;

    @Size( max = 100 )
    private String field13;

    @Size( max = 100 )
    private String field14;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( BigDecimal id ) {
        this.id = id ;
    }

    public BigDecimal getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSystemId( BigDecimal systemId ) {
        this.systemId = systemId;
    }
    public BigDecimal getSystemId() {
        return this.systemId;
    }

    public void setProductName( String productName ) {
        this.productName = productName;
    }
    public String getProductName() {
        return this.productName;
    }

    public void setDocName( String docName ) {
        this.docName = docName;
    }
    public String getDocName() {
        return this.docName;
    }

    public void setDocDescription( String docDescription ) {
        this.docDescription = docDescription;
    }
    public String getDocDescription() {
        return this.docDescription;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setField1( String field1 ) {
        this.field1 = field1;
    }
    public String getField1() {
        return this.field1;
    }

    public void setField2( String field2 ) {
        this.field2 = field2;
    }
    public String getField2() {
        return this.field2;
    }

    public void setField3( String field3 ) {
        this.field3 = field3;
    }
    public String getField3() {
        return this.field3;
    }

    public void setField4( String field4 ) {
        this.field4 = field4;
    }
    public String getField4() {
        return this.field4;
    }

    public void setField5( String field5 ) {
        this.field5 = field5;
    }
    public String getField5() {
        return this.field5;
    }

    public void setField6( String field6 ) {
        this.field6 = field6;
    }
    public String getField6() {
        return this.field6;
    }

    public void setField7( String field7 ) {
        this.field7 = field7;
    }
    public String getField7() {
        return this.field7;
    }

    public void setField8( String field8 ) {
        this.field8 = field8;
    }
    public String getField8() {
        return this.field8;
    }

    public void setField9( String field9 ) {
        this.field9 = field9;
    }
    public String getField9() {
        return this.field9;
    }

    public void setField10( String field10 ) {
        this.field10 = field10;
    }
    public String getField10() {
        return this.field10;
    }

    public void setField11( String field11 ) {
        this.field11 = field11;
    }
    public String getField11() {
        return this.field11;
    }

    public void setField12( String field12 ) {
        this.field12 = field12;
    }
    public String getField12() {
        return this.field12;
    }

    public void setField13( String field13 ) {
        this.field13 = field13;
    }
    public String getField13() {
        return this.field13;
    }

    public void setField14( String field14 ) {
        this.field14 = field14;
    }
    public String getField14() {
        return this.field14;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(systemId);
        sb.append("|");
        sb.append(productName);
        sb.append("|");
        sb.append(docName);
        sb.append("|");
        sb.append(docDescription);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(field1);
        sb.append("|");
        sb.append(field2);
        sb.append("|");
        sb.append(field3);
        sb.append("|");
        sb.append(field4);
        sb.append("|");
        sb.append(field5);
        sb.append("|");
        sb.append(field6);
        sb.append("|");
        sb.append(field7);
        sb.append("|");
        sb.append(field8);
        sb.append("|");
        sb.append(field9);
        sb.append("|");
        sb.append(field10);
        sb.append("|");
        sb.append(field11);
        sb.append("|");
        sb.append(field12);
        sb.append("|");
        sb.append(field13);
        sb.append("|");
        sb.append(field14);
        return sb.toString(); 
    } 


}
