/*
 * Created on 2022-04-14 ( Time 15:22:17 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;
import java.util.Date;

public class IapprPinOtp implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private BigDecimal id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 30 )
    private String pin;

    @NotNull
    @Size( min = 1, max = 30 )
    private String userId;

    @NotNull
    @Size( min = 1, max = 30 )
    private String deviceId;

    @NotNull
    private Date createdOn;


    private Date modifiedOn;

    @Size( max = 50 )
    private String modifiedBy;

    @NotNull
    @Size( min = 1, max = 30 )
    private String status;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( BigDecimal id ) {
        this.id = id ;
    }

    public BigDecimal getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPin( String pin ) {
        this.pin = pin;
    }
    public String getPin() {
        return this.pin;
    }

    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    public void setDeviceId( String deviceId ) {
        this.deviceId = deviceId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(pin);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(deviceId);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 


}
