/*
 * Created on 2022-04-14 ( Time 09:45:06 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.vpbank.innovation.bean.FvUser;
import com.vpbank.innovation.bean.jpa.FvUserEntity;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import com.vpbank.innovation.business.service.FvUserService;
import com.vpbank.innovation.business.service.mapping.FvUserServiceMapper;
import com.vpbank.innovation.data.repository.jpa.FvUserJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of FvUserService
 */
@Component
@Transactional
public class FvUserServiceImpl implements FvUserService {

	@Resource
	private FvUserJpaRepository fvUserJpaRepository;

	@Resource
	private FvUserServiceMapper fvUserServiceMapper;
	
	@Override
	public FvUser findById(BigDecimal id) {
		FvUserEntity fvUserEntity = fvUserJpaRepository.findOne(id);
		return fvUserServiceMapper.mapFvUserEntityToFvUser(fvUserEntity);
	}

	@Override
	public List<FvUser> findAll() {
		Iterable<FvUserEntity> entities = fvUserJpaRepository.findAll();
		List<FvUser> beans = new ArrayList<FvUser>();
		for(FvUserEntity fvUserEntity : entities) {
			beans.add(fvUserServiceMapper.mapFvUserEntityToFvUser(fvUserEntity));
		}
		return beans;
	}

	@Override
	public FvUser save(FvUser fvUser) {
		return update(fvUser) ;
	}

	@Override
	public FvUser create(FvUser fvUser) {
		FvUserEntity fvUserEntity = new FvUserEntity();
		fvUserServiceMapper.mapFvUserToFvUserEntity(fvUser, fvUserEntity);
		FvUserEntity fvUserEntitySaved = fvUserJpaRepository.save(fvUserEntity);
		return fvUserServiceMapper.mapFvUserEntityToFvUser(fvUserEntitySaved);
	}

	@Override
	public FvUser update(FvUser fvUser) {
		FvUserEntity fvUserEntity = fvUserJpaRepository.findOne(fvUser.getId());
		fvUserServiceMapper.mapFvUserToFvUserEntity(fvUser, fvUserEntity);
		FvUserEntity fvUserEntitySaved = fvUserJpaRepository.save(fvUserEntity);
		return fvUserServiceMapper.mapFvUserEntityToFvUser(fvUserEntitySaved);
	}

	@Override
	public void delete(BigDecimal id) {
		fvUserJpaRepository.delete(id);
	}

	public FvUserJpaRepository getFvUserJpaRepository() {
		return fvUserJpaRepository;
	}

	public void setFvUserJpaRepository(FvUserJpaRepository fvUserJpaRepository) {
		this.fvUserJpaRepository = fvUserJpaRepository;
	}

	public FvUserServiceMapper getFvUserServiceMapper() {
		return fvUserServiceMapper;
	}

	public void setFvUserServiceMapper(FvUserServiceMapper fvUserServiceMapper) {
		this.fvUserServiceMapper = fvUserServiceMapper;
	}

}
