/*
 * Created on 2022-04-14 ( Time 15:22:14 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.vpbank.innovation.bean.IapprCodeOtp;
import com.vpbank.innovation.bean.jpa.IapprCodeOtpEntity;
import java.math.BigDecimal;
import java.util.Date;
import com.vpbank.innovation.business.service.IapprCodeOtpService;
import com.vpbank.innovation.business.service.mapping.IapprCodeOtpServiceMapper;
import com.vpbank.innovation.data.repository.jpa.IapprCodeOtpJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of IapprCodeOtpService
 */
@Component
@Transactional
public class IapprCodeOtpServiceImpl implements IapprCodeOtpService {

	@Resource
	private IapprCodeOtpJpaRepository iapprCodeOtpJpaRepository;

	@Resource
	private IapprCodeOtpServiceMapper iapprCodeOtpServiceMapper;
	
	@Override
	public IapprCodeOtp findById(BigDecimal id) {
		IapprCodeOtpEntity iapprCodeOtpEntity = iapprCodeOtpJpaRepository.findOne(id);
		return iapprCodeOtpServiceMapper.mapIapprCodeOtpEntityToIapprCodeOtp(iapprCodeOtpEntity);
	}

	@Override
	public List<IapprCodeOtp> findAll() {
		Iterable<IapprCodeOtpEntity> entities = iapprCodeOtpJpaRepository.findAll();
		List<IapprCodeOtp> beans = new ArrayList<IapprCodeOtp>();
		for(IapprCodeOtpEntity iapprCodeOtpEntity : entities) {
			beans.add(iapprCodeOtpServiceMapper.mapIapprCodeOtpEntityToIapprCodeOtp(iapprCodeOtpEntity));
		}
		return beans;
	}

	@Override
	public IapprCodeOtp save(IapprCodeOtp iapprCodeOtp) {
		return update(iapprCodeOtp) ;
	}

	@Override
	public IapprCodeOtp create(IapprCodeOtp iapprCodeOtp) {
		IapprCodeOtpEntity iapprCodeOtpEntity = new IapprCodeOtpEntity();
		iapprCodeOtpServiceMapper.mapIapprCodeOtpToIapprCodeOtpEntity(iapprCodeOtp, iapprCodeOtpEntity);
		IapprCodeOtpEntity iapprCodeOtpEntitySaved = iapprCodeOtpJpaRepository.save(iapprCodeOtpEntity);
		return iapprCodeOtpServiceMapper.mapIapprCodeOtpEntityToIapprCodeOtp(iapprCodeOtpEntitySaved);
	}

	@Override
	public IapprCodeOtp update(IapprCodeOtp iapprCodeOtp) {
		IapprCodeOtpEntity iapprCodeOtpEntity = iapprCodeOtpJpaRepository.findOne(iapprCodeOtp.getId());
		iapprCodeOtpServiceMapper.mapIapprCodeOtpToIapprCodeOtpEntity(iapprCodeOtp, iapprCodeOtpEntity);
		IapprCodeOtpEntity iapprCodeOtpEntitySaved = iapprCodeOtpJpaRepository.save(iapprCodeOtpEntity);
		return iapprCodeOtpServiceMapper.mapIapprCodeOtpEntityToIapprCodeOtp(iapprCodeOtpEntitySaved);
	}

	@Override
	public void delete(BigDecimal id) {
		iapprCodeOtpJpaRepository.delete(id);
	}

	public IapprCodeOtpJpaRepository getIapprCodeOtpJpaRepository() {
		return iapprCodeOtpJpaRepository;
	}

	public void setIapprCodeOtpJpaRepository(IapprCodeOtpJpaRepository iapprCodeOtpJpaRepository) {
		this.iapprCodeOtpJpaRepository = iapprCodeOtpJpaRepository;
	}

	public IapprCodeOtpServiceMapper getIapprCodeOtpServiceMapper() {
		return iapprCodeOtpServiceMapper;
	}

	public void setIapprCodeOtpServiceMapper(IapprCodeOtpServiceMapper iapprCodeOtpServiceMapper) {
		this.iapprCodeOtpServiceMapper = iapprCodeOtpServiceMapper;
	}

}
