/*
 * Created on 2022-04-14 ( Time 15:22:28 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.vpbank.innovation.bean.IapprPinOtp;
import com.vpbank.innovation.bean.jpa.IapprPinOtpEntity;
import java.math.BigDecimal;
import java.util.Date;
import com.vpbank.innovation.business.service.IapprPinOtpService;
import com.vpbank.innovation.business.service.mapping.IapprPinOtpServiceMapper;
import com.vpbank.innovation.data.repository.jpa.IapprPinOtpJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of IapprPinOtpService
 */
@Component
@Transactional
public class IapprPinOtpServiceImpl implements IapprPinOtpService {

	@Resource
	private IapprPinOtpJpaRepository iapprPinOtpJpaRepository;

	@Resource
	private IapprPinOtpServiceMapper iapprPinOtpServiceMapper;
	
	@Override
	public IapprPinOtp findById(BigDecimal id) {
		IapprPinOtpEntity iapprPinOtpEntity = iapprPinOtpJpaRepository.findOne(id);
		return iapprPinOtpServiceMapper.mapIapprPinOtpEntityToIapprPinOtp(iapprPinOtpEntity);
	}

	@Override
	public List<IapprPinOtp> findAll() {
		Iterable<IapprPinOtpEntity> entities = iapprPinOtpJpaRepository.findAll();
		List<IapprPinOtp> beans = new ArrayList<IapprPinOtp>();
		for(IapprPinOtpEntity iapprPinOtpEntity : entities) {
			beans.add(iapprPinOtpServiceMapper.mapIapprPinOtpEntityToIapprPinOtp(iapprPinOtpEntity));
		}
		return beans;
	}

	@Override
	public IapprPinOtp save(IapprPinOtp iapprPinOtp) {
		return update(iapprPinOtp) ;
	}

	@Override
	public IapprPinOtp create(IapprPinOtp iapprPinOtp) {
		IapprPinOtpEntity iapprPinOtpEntity = new IapprPinOtpEntity();
		iapprPinOtpServiceMapper.mapIapprPinOtpToIapprPinOtpEntity(iapprPinOtp, iapprPinOtpEntity);
		IapprPinOtpEntity iapprPinOtpEntitySaved = iapprPinOtpJpaRepository.save(iapprPinOtpEntity);
		return iapprPinOtpServiceMapper.mapIapprPinOtpEntityToIapprPinOtp(iapprPinOtpEntitySaved);
	}

	@Override
	public IapprPinOtp update(IapprPinOtp iapprPinOtp) {
		IapprPinOtpEntity iapprPinOtpEntity = iapprPinOtpJpaRepository.findOne(iapprPinOtp.getId());
		iapprPinOtpServiceMapper.mapIapprPinOtpToIapprPinOtpEntity(iapprPinOtp, iapprPinOtpEntity);
		IapprPinOtpEntity iapprPinOtpEntitySaved = iapprPinOtpJpaRepository.save(iapprPinOtpEntity);
		return iapprPinOtpServiceMapper.mapIapprPinOtpEntityToIapprPinOtp(iapprPinOtpEntitySaved);
	}

	@Override
	public void delete(BigDecimal id) {
		iapprPinOtpJpaRepository.delete(id);
	}

	public IapprPinOtpJpaRepository getIapprPinOtpJpaRepository() {
		return iapprPinOtpJpaRepository;
	}

	public void setIapprPinOtpJpaRepository(IapprPinOtpJpaRepository iapprPinOtpJpaRepository) {
		this.iapprPinOtpJpaRepository = iapprPinOtpJpaRepository;
	}

	public IapprPinOtpServiceMapper getIapprPinOtpServiceMapper() {
		return iapprPinOtpServiceMapper;
	}

	public void setIapprPinOtpServiceMapper(IapprPinOtpServiceMapper iapprPinOtpServiceMapper) {
		this.iapprPinOtpServiceMapper = iapprPinOtpServiceMapper;
	}

}
