/*
 * Created on 2022-04-12 ( Time 14:44:12 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service;

import java.util.List;

import com.vpbank.innovation.bean.DmsDocumentM;

/**
 * Business Service Interface for entity DmsDocumentM.
 */
public interface DmsDocumentMService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DmsDocumentM findById( BigDecimal id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DmsDocumentM> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DmsDocumentM save(DmsDocumentM entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DmsDocumentM update(DmsDocumentM entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DmsDocumentM create(DmsDocumentM entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( BigDecimal id );


}
