/*
 * Created on 2022-04-14 ( Time 15:22:27 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service;

import java.util.List;

import com.vpbank.innovation.bean.IapprPinOtp;

/**
 * Business Service Interface for entity IapprPinOtp.
 */
public interface IapprPinOtpService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	IapprPinOtp findById( BigDecimal id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<IapprPinOtp> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	IapprPinOtp save(IapprPinOtp entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	IapprPinOtp update(IapprPinOtp entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	IapprPinOtp create(IapprPinOtp entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( BigDecimal id );


}
