/*
 * Created on 2022-04-14 ( Time 15:22:12 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service;

import java.util.List;

import com.vpbank.innovation.bean.IapprCodeOtp;

/**
 * Business Service Interface for entity IapprCodeOtp.
 */
public interface IapprCodeOtpService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	IapprCodeOtp findById( BigDecimal id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<IapprCodeOtp> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	IapprCodeOtp save(IapprCodeOtp entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	IapprCodeOtp update(IapprCodeOtp entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	IapprCodeOtp create(IapprCodeOtp entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( BigDecimal id );


}
