/*
 * Created on 2022-04-12 ( Time 14:44:14 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.vpbank.innovation.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "DMS_DOCUMENT_M"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="DMS_DOCUMENT_M", schema="LOS_OWNER" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DmsDocumentMEntity.countAll", query="SELECT COUNT(x) FROM DmsDocumentMEntity x" )
} )
public class DmsDocumentMEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    @SequenceGenerator(name="SEQ_GEN", sequenceName="DMS_DOCUMENT_M_SEQ", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
    private BigDecimal id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="PRODUCT_NAME", nullable=false, length=100)
    private String     productName  ;

    @Column(name="DOC_NAME", nullable=false, length=100)
    private String     docName      ;

    @Column(name="DOC_DESCRIPTION", length=255)
    private String     docDescription ;

    @Column(name="CREATED_BY", nullable=false, length=255)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_ON", nullable=false)
    private Date       createdOn    ;

    @Column(name="MODIFIED_BY", nullable=false, length=255)
    private String     modifiedBy   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_ON", nullable=false)
    private Date       modifiedOn   ;

    @Column(name="FIELD_1", length=100)
    private String     field1       ;

    @Column(name="FIELD_2", length=100)
    private String     field2       ;

    @Column(name="FIELD_3", length=100)
    private String     field3       ;

    @Column(name="FIELD_4", length=100)
    private String     field4       ;

    @Column(name="FIELD_5", length=100)
    private String     field5       ;

    @Column(name="FIELD_6", length=100)
    private String     field6       ;

    @Column(name="FIELD_7", length=100)
    private String     field7       ;

    @Column(name="FIELD_8", length=100)
    private String     field8       ;

    @Column(name="FIELD_9", length=100)
    private String     field9       ;

    @Column(name="FIELD_10", length=100)
    private String     field10      ;

    @Column(name="FIELD_11", length=100)
    private String     field11      ;

    @Column(name="FIELD_12", length=100)
    private String     field12      ;

    @Column(name="FIELD_13", length=100)
    private String     field13      ;

    @Column(name="FIELD_14", length=100)
    private String     field14      ;

	// "systemId" (column "SYSTEM_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="SYSTEM_ID", referencedColumnName="ID")
    private DmsSystemEntity dmsSystem   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DmsDocumentMEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( BigDecimal id ) {
        this.id = id ;
    }
    public BigDecimal getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : PRODUCT_NAME ( VARCHAR2 ) 
    public void setProductName( String productName ) {
        this.productName = productName;
    }
    public String getProductName() {
        return this.productName;
    }

    //--- DATABASE MAPPING : DOC_NAME ( VARCHAR2 ) 
    public void setDocName( String docName ) {
        this.docName = docName;
    }
    public String getDocName() {
        return this.docName;
    }

    //--- DATABASE MAPPING : DOC_DESCRIPTION ( VARCHAR2 ) 
    public void setDocDescription( String docDescription ) {
        this.docDescription = docDescription;
    }
    public String getDocDescription() {
        return this.docDescription;
    }

    //--- DATABASE MAPPING : CREATED_BY ( VARCHAR2 ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : CREATED_ON ( DATE ) 
    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    //--- DATABASE MAPPING : MODIFIED_BY ( VARCHAR2 ) 
    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    //--- DATABASE MAPPING : MODIFIED_ON ( DATE ) 
    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    //--- DATABASE MAPPING : FIELD_1 ( VARCHAR2 ) 
    public void setField1( String field1 ) {
        this.field1 = field1;
    }
    public String getField1() {
        return this.field1;
    }

    //--- DATABASE MAPPING : FIELD_2 ( VARCHAR2 ) 
    public void setField2( String field2 ) {
        this.field2 = field2;
    }
    public String getField2() {
        return this.field2;
    }

    //--- DATABASE MAPPING : FIELD_3 ( VARCHAR2 ) 
    public void setField3( String field3 ) {
        this.field3 = field3;
    }
    public String getField3() {
        return this.field3;
    }

    //--- DATABASE MAPPING : FIELD_4 ( VARCHAR2 ) 
    public void setField4( String field4 ) {
        this.field4 = field4;
    }
    public String getField4() {
        return this.field4;
    }

    //--- DATABASE MAPPING : FIELD_5 ( VARCHAR2 ) 
    public void setField5( String field5 ) {
        this.field5 = field5;
    }
    public String getField5() {
        return this.field5;
    }

    //--- DATABASE MAPPING : FIELD_6 ( VARCHAR2 ) 
    public void setField6( String field6 ) {
        this.field6 = field6;
    }
    public String getField6() {
        return this.field6;
    }

    //--- DATABASE MAPPING : FIELD_7 ( VARCHAR2 ) 
    public void setField7( String field7 ) {
        this.field7 = field7;
    }
    public String getField7() {
        return this.field7;
    }

    //--- DATABASE MAPPING : FIELD_8 ( VARCHAR2 ) 
    public void setField8( String field8 ) {
        this.field8 = field8;
    }
    public String getField8() {
        return this.field8;
    }

    //--- DATABASE MAPPING : FIELD_9 ( VARCHAR2 ) 
    public void setField9( String field9 ) {
        this.field9 = field9;
    }
    public String getField9() {
        return this.field9;
    }

    //--- DATABASE MAPPING : FIELD_10 ( VARCHAR2 ) 
    public void setField10( String field10 ) {
        this.field10 = field10;
    }
    public String getField10() {
        return this.field10;
    }

    //--- DATABASE MAPPING : FIELD_11 ( VARCHAR2 ) 
    public void setField11( String field11 ) {
        this.field11 = field11;
    }
    public String getField11() {
        return this.field11;
    }

    //--- DATABASE MAPPING : FIELD_12 ( VARCHAR2 ) 
    public void setField12( String field12 ) {
        this.field12 = field12;
    }
    public String getField12() {
        return this.field12;
    }

    //--- DATABASE MAPPING : FIELD_13 ( VARCHAR2 ) 
    public void setField13( String field13 ) {
        this.field13 = field13;
    }
    public String getField13() {
        return this.field13;
    }

    //--- DATABASE MAPPING : FIELD_14 ( VARCHAR2 ) 
    public void setField14( String field14 ) {
        this.field14 = field14;
    }
    public String getField14() {
        return this.field14;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDmsSystem( DmsSystemEntity dmsSystem ) {
        this.dmsSystem = dmsSystem;
    }
    public DmsSystemEntity getDmsSystem() {
        return this.dmsSystem;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(productName);
        sb.append("|");
        sb.append(docName);
        sb.append("|");
        sb.append(docDescription);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(field1);
        sb.append("|");
        sb.append(field2);
        sb.append("|");
        sb.append(field3);
        sb.append("|");
        sb.append(field4);
        sb.append("|");
        sb.append(field5);
        sb.append("|");
        sb.append(field6);
        sb.append("|");
        sb.append(field7);
        sb.append("|");
        sb.append(field8);
        sb.append("|");
        sb.append(field9);
        sb.append("|");
        sb.append(field10);
        sb.append("|");
        sb.append(field11);
        sb.append("|");
        sb.append(field12);
        sb.append("|");
        sb.append(field13);
        sb.append("|");
        sb.append(field14);
        return sb.toString(); 
    } 

}
