/*
 * Created on 2022-04-14 ( Time 15:22:30 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.vpbank.innovation.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "IAPPR_PIN_OTP"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="IAPPR_PIN_OTP", schema="EDOC_OWNER" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="IapprPinOtpEntity.countAll", query="SELECT COUNT(x) FROM IapprPinOtpEntity x" )
} )
public class IapprPinOtpEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    @SequenceGenerator(name="SEQ_GEN", sequenceName="IAPPR_PIN_OTP_SEQ", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
    private BigDecimal id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="PIN", nullable=false, length=30)
    private String     pin          ;

    @Column(name="USER_ID", nullable=false, length=30)
    private String     userId       ;

    @Column(name="DEVICE_ID", nullable=false, length=30)
    private String     deviceId     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_ON", nullable=false)
    private Date       createdOn    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_ON")
    private Date       modifiedOn   ;

    @Column(name="MODIFIED_BY", length=50)
    private String     modifiedBy   ;

    @Column(name="STATUS", nullable=false, length=30)
    private String     status       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public IapprPinOtpEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( BigDecimal id ) {
        this.id = id ;
    }
    public BigDecimal getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : PIN ( VARCHAR2 ) 
    public void setPin( String pin ) {
        this.pin = pin;
    }
    public String getPin() {
        return this.pin;
    }

    //--- DATABASE MAPPING : USER_ID ( VARCHAR2 ) 
    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    //--- DATABASE MAPPING : DEVICE_ID ( VARCHAR2 ) 
    public void setDeviceId( String deviceId ) {
        this.deviceId = deviceId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }

    //--- DATABASE MAPPING : CREATED_ON ( TIMESTAMP(6) ) 
    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    //--- DATABASE MAPPING : MODIFIED_ON ( TIMESTAMP(6) ) 
    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    //--- DATABASE MAPPING : MODIFIED_BY ( VARCHAR2 ) 
    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    //--- DATABASE MAPPING : STATUS ( VARCHAR2 ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(pin);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(deviceId);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
