/*
 * Created on 2022-04-14 ( Time 15:22:15 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.vpbank.innovation.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "IAPPR_CODE_OTP"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="IAPPR_CODE_OTP", schema="EDOC_OWNER" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="IapprCodeOtpEntity.countAll", query="SELECT COUNT(x) FROM IapprCodeOtpEntity x" )
} )
public class IapprCodeOtpEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    @SequenceGenerator(name="SEQ_GEN", sequenceName="IAPPR_CODE_OTP_SEQ", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
    private BigDecimal id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="CODE", nullable=false, length=30)
    private String     code         ;

    @Column(name="USER_ID", nullable=false, length=30)
    private String     userId       ;

    @Column(name="STATUS", nullable=false, length=30)
    private String     status       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_ON", nullable=false)
    private Date       createdOn    ;

    @Column(name="EXPIRE_TIME", nullable=false, length=30)
    private String     expireTime   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public IapprCodeOtpEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( BigDecimal id ) {
        this.id = id ;
    }
    public BigDecimal getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : CODE ( VARCHAR2 ) 
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    //--- DATABASE MAPPING : USER_ID ( VARCHAR2 ) 
    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    //--- DATABASE MAPPING : STATUS ( VARCHAR2 ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : CREATED_ON ( TIMESTAMP(6) ) 
    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    //--- DATABASE MAPPING : EXPIRE_TIME ( VARCHAR2 ) 
    public void setExpireTime( String expireTime ) {
        this.expireTime = expireTime;
    }
    public String getExpireTime() {
        return this.expireTime;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(code);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(expireTime);
        return sb.toString(); 
    } 

}
