/*
 * Created on 2022-04-14 ( Time 15:22:25 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.vpbank.innovation.bean.IapprPinOtp;
import com.vpbank.innovation.business.service.IapprPinOtpService;
import com.vpbank.innovation.web.listitem.IapprPinOtpListItem;

/**
 * Spring MVC controller for 'IapprPinOtp' management.
 */
@Controller
public class IapprPinOtpRestController {

	@Resource
	private IapprPinOtpService iapprPinOtpService;
	
	@RequestMapping( value="/items/iapprPinOtp",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<IapprPinOtpListItem> findAllAsListItems() {
		List<IapprPinOtp> list = iapprPinOtpService.findAll();
		List<IapprPinOtpListItem> items = new LinkedList<IapprPinOtpListItem>();
		for ( IapprPinOtp iapprPinOtp : list ) {
			items.add(new IapprPinOtpListItem( iapprPinOtp ) );
		}
		return items;
	}
	
	@RequestMapping( value="/iapprPinOtp",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<IapprPinOtp> findAll() {
		return iapprPinOtpService.findAll();
	}

	@RequestMapping( value="/iapprPinOtp/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public IapprPinOtp findOne(@PathVariable("id") BigDecimal id) {
		return iapprPinOtpService.findById(id);
	}
	
	@RequestMapping( value="/iapprPinOtp",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public IapprPinOtp create(@RequestBody IapprPinOtp iapprPinOtp) {
		return iapprPinOtpService.create(iapprPinOtp);
	}

	@RequestMapping( value="/iapprPinOtp/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public IapprPinOtp update(@PathVariable("id") BigDecimal id, @RequestBody IapprPinOtp iapprPinOtp) {
		return iapprPinOtpService.update(iapprPinOtp);
	}

	@RequestMapping( value="/iapprPinOtp/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") BigDecimal id) {
		iapprPinOtpService.delete(id);
	}
	
}
