/*
 * Created on 2022-04-14 ( Time 15:22:10 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.vpbank.innovation.bean.IapprCodeOtp;
import com.vpbank.innovation.business.service.IapprCodeOtpService;
import com.vpbank.innovation.web.listitem.IapprCodeOtpListItem;

/**
 * Spring MVC controller for 'IapprCodeOtp' management.
 */
@Controller
public class IapprCodeOtpRestController {

	@Resource
	private IapprCodeOtpService iapprCodeOtpService;
	
	@RequestMapping( value="/items/iapprCodeOtp",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<IapprCodeOtpListItem> findAllAsListItems() {
		List<IapprCodeOtp> list = iapprCodeOtpService.findAll();
		List<IapprCodeOtpListItem> items = new LinkedList<IapprCodeOtpListItem>();
		for ( IapprCodeOtp iapprCodeOtp : list ) {
			items.add(new IapprCodeOtpListItem( iapprCodeOtp ) );
		}
		return items;
	}
	
	@RequestMapping( value="/iapprCodeOtp",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<IapprCodeOtp> findAll() {
		return iapprCodeOtpService.findAll();
	}

	@RequestMapping( value="/iapprCodeOtp/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public IapprCodeOtp findOne(@PathVariable("id") BigDecimal id) {
		return iapprCodeOtpService.findById(id);
	}
	
	@RequestMapping( value="/iapprCodeOtp",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public IapprCodeOtp create(@RequestBody IapprCodeOtp iapprCodeOtp) {
		return iapprCodeOtpService.create(iapprCodeOtp);
	}

	@RequestMapping( value="/iapprCodeOtp/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public IapprCodeOtp update(@PathVariable("id") BigDecimal id, @RequestBody IapprCodeOtp iapprCodeOtp) {
		return iapprCodeOtpService.update(iapprCodeOtp);
	}

	@RequestMapping( value="/iapprCodeOtp/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") BigDecimal id) {
		iapprCodeOtpService.delete(id);
	}
	
}
