/*
 * Created on 2022-04-12 ( Time 14:44:06 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.web.listitem;

import com.vpbank.innovation.bean.DmsDocumentM;
import com.vpbank.innovation.web.common.ListItem;

public class DmsDocumentMListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public DmsDocumentMListItem(DmsDocumentM dmsDocumentM) {
		super();

		this.value = ""
			 + dmsDocumentM.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = dmsDocumentM.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
