/*
 * Created on 2022-04-14 ( Time 09:45:05 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.web.listitem;

import com.vpbank.innovation.bean.FvUser;
import com.vpbank.innovation.web.common.ListItem;

public class FvUserListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public FvUserListItem(FvUser fvUser) {
		super();

		this.value = ""
			 + fvUser.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = fvUser.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
