/*
 * Created on 2022-04-14 ( Time 15:22:18 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.web.listitem;

import com.vpbank.innovation.bean.IapprPinOtp;
import com.vpbank.innovation.web.common.ListItem;

public class IapprPinOtpListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public IapprPinOtpListItem(IapprPinOtp iapprPinOtp) {
		super();

		this.value = ""
			 + iapprPinOtp.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = iapprPinOtp.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
