/*
 * Created on 2022-04-14 ( Time 15:22:03 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.web.listitem;

import com.vpbank.innovation.bean.IapprCodeOtp;
import com.vpbank.innovation.web.common.ListItem;

public class IapprCodeOtpListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public IapprCodeOtpListItem(IapprCodeOtp iapprCodeOtp) {
		super();

		this.value = ""
			 + iapprCodeOtp.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = iapprCodeOtp.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
