/*
 * Created on 2022-04-12 ( Time 14:44:07 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.vpbank.innovation.web.common.AbstractController;
import com.vpbank.innovation.web.common.FormMode;
import com.vpbank.innovation.web.common.Message;
import com.vpbank.innovation.web.common.MessageType;

//--- Entities
import com.vpbank.innovation.bean.DmsDocumentM;
import com.vpbank.innovation.bean.DmsSystem;

//--- Services 
import com.vpbank.innovation.business.service.DmsDocumentMService;
import com.vpbank.innovation.business.service.DmsSystemService;

//--- List Items 
import com.vpbank.innovation.web.listitem.DmsSystemListItem;

/**
 * Spring MVC controller for 'DmsDocumentM' management.
 */
@Controller
@RequestMapping("/dmsDocumentM")
public class DmsDocumentMController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "dmsDocumentM";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "dmsDocumentM/form";
	private static final String JSP_LIST   = "dmsDocumentM/list";
	private static final String JSP_DETAIL   = "dmsDocumentM/detail";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/dmsDocumentM/create";
	private static final String SAVE_ACTION_UPDATE   = "/dmsDocumentM/update";

	//--- Main entity service
	@Resource
    private DmsDocumentMService dmsDocumentMService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private DmsSystemService dmsSystemService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public DmsDocumentMController() {
		super(DmsDocumentMController.class, MAIN_ENTITY_NAME );
		log("DmsDocumentMController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "DmsSystem"
	 * @param model
	 */
	private void populateListOfDmsSystemItems(Model model) {
		List<DmsSystem> list = dmsSystemService.findAll();
		List<DmsSystemListItem> items = new LinkedList<DmsSystemListItem>();
		for ( DmsSystem dmsSystem : list ) {
			items.add(new DmsSystemListItem( dmsSystem ) );
		}
		model.addAttribute("listOfDmsSystemItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param dmsDocumentM
	 */
	private void populateModel(Model model, DmsDocumentM dmsDocumentM, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, dmsDocumentM);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfDmsSystemItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfDmsSystemItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of DmsDocumentM found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<DmsDocumentM> list = dmsDocumentMService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a detail item of selected DmsDocumentM found in the database
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping("/detail/{id}")
	public String detail(Model model, @PathVariable("id") BigDecimal id) {
		log("Action 'detail'");
		DmsDocumentM dmsDocumentM = dmsDocumentMService.findById(id);
		//populateProcessDefInfoToModel(model, {id}.toString());
		model.addAttribute(MAIN_ENTITY_NAME, dmsDocumentM);		
		return JSP_DETAIL;
	}

	/**
	 * Shows a form page in order to create a new DmsDocumentM
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		DmsDocumentM dmsDocumentM = new DmsDocumentM();	
		populateModel( model, dmsDocumentM, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing DmsDocumentM
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") BigDecimal id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		DmsDocumentM dmsDocumentM = dmsDocumentMService.findById(id);
		populateModel( model, dmsDocumentM, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to submit item into workflow with an existing DmsDocumentM
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/submit/{id}")
	public String submit(Model model, @PathVariable("id") BigDecimal id ) {
		log("Action 'submit'");
		//--- Search the entity by its primary key and stores it in the model 
		/*
		DmsDocumentM dmsDocumentM = dmsDocumentMService.findById(id);
		if (dmsDocumentM != null && dmsDocumentM.getAppIdC() != null)
			dmsDocumentMService.submitToWorkflow(dmsDocumentM);
        */
		return redirectToList();
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param dmsDocumentM  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid DmsDocumentM dmsDocumentM, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				DmsDocumentM dmsDocumentMCreated = dmsDocumentMService.create(dmsDocumentM); 
				model.addAttribute(MAIN_ENTITY_NAME, dmsDocumentMCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToList();
			} else {
				populateModel( model, dmsDocumentM, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "dmsDocumentM.error.create", e);
			populateModel( model, dmsDocumentM, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param dmsDocumentM  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid DmsDocumentM dmsDocumentM, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				DmsDocumentM dmsDocumentMSaved = dmsDocumentMService.update(dmsDocumentM);
				model.addAttribute(MAIN_ENTITY_NAME, dmsDocumentMSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToList();
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, dmsDocumentM, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "dmsDocumentM.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, dmsDocumentM, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") BigDecimal id) {
		log("Action 'delete'" );
		try {
			dmsDocumentMService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "dmsDocumentM.error.delete", e);
		}
		return redirectToList();
	}

}
