/*
 * Created on 2022-04-14 ( Time 15:22:18 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.vpbank.innovation.web.common.AbstractController;
import com.vpbank.innovation.web.common.FormMode;
import com.vpbank.innovation.web.common.Message;
import com.vpbank.innovation.web.common.MessageType;

//--- Entities
import com.vpbank.innovation.bean.IapprPinOtp;

//--- Services 
import com.vpbank.innovation.business.service.IapprPinOtpService;


/**
 * Spring MVC controller for 'IapprPinOtp' management.
 */
@Controller
@RequestMapping("/iapprPinOtp")
public class IapprPinOtpController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "iapprPinOtp";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "iapprPinOtp/form";
	private static final String JSP_LIST   = "iapprPinOtp/list";
	private static final String JSP_DETAIL   = "iapprPinOtp/detail";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/iapprPinOtp/create";
	private static final String SAVE_ACTION_UPDATE   = "/iapprPinOtp/update";

	//--- Main entity service
	@Resource
    private IapprPinOtpService iapprPinOtpService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public IapprPinOtpController() {
		super(IapprPinOtpController.class, MAIN_ENTITY_NAME );
		log("IapprPinOtpController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param iapprPinOtp
	 */
	private void populateModel(Model model, IapprPinOtp iapprPinOtp, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, iapprPinOtp);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of IapprPinOtp found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<IapprPinOtp> list = iapprPinOtpService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a detail item of selected IapprPinOtp found in the database
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping("/detail/{id}")
	public String detail(Model model, @PathVariable("id") BigDecimal id) {
		log("Action 'detail'");
		IapprPinOtp iapprPinOtp = iapprPinOtpService.findById(id);
		//populateProcessDefInfoToModel(model, {id}.toString());
		model.addAttribute(MAIN_ENTITY_NAME, iapprPinOtp);		
		return JSP_DETAIL;
	}

	/**
	 * Shows a form page in order to create a new IapprPinOtp
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		IapprPinOtp iapprPinOtp = new IapprPinOtp();	
		populateModel( model, iapprPinOtp, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing IapprPinOtp
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") BigDecimal id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		IapprPinOtp iapprPinOtp = iapprPinOtpService.findById(id);
		populateModel( model, iapprPinOtp, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to submit item into workflow with an existing IapprPinOtp
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/submit/{id}")
	public String submit(Model model, @PathVariable("id") BigDecimal id ) {
		log("Action 'submit'");
		//--- Search the entity by its primary key and stores it in the model 
		/*
		IapprPinOtp iapprPinOtp = iapprPinOtpService.findById(id);
		if (iapprPinOtp != null && iapprPinOtp.getAppIdC() != null)
			iapprPinOtpService.submitToWorkflow(iapprPinOtp);
        */
		return redirectToList();
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param iapprPinOtp  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid IapprPinOtp iapprPinOtp, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				IapprPinOtp iapprPinOtpCreated = iapprPinOtpService.create(iapprPinOtp); 
				model.addAttribute(MAIN_ENTITY_NAME, iapprPinOtpCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToList();
			} else {
				populateModel( model, iapprPinOtp, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "iapprPinOtp.error.create", e);
			populateModel( model, iapprPinOtp, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param iapprPinOtp  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid IapprPinOtp iapprPinOtp, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				IapprPinOtp iapprPinOtpSaved = iapprPinOtpService.update(iapprPinOtp);
				model.addAttribute(MAIN_ENTITY_NAME, iapprPinOtpSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToList();
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, iapprPinOtp, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "iapprPinOtp.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, iapprPinOtp, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") BigDecimal id) {
		log("Action 'delete'" );
		try {
			iapprPinOtpService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "iapprPinOtp.error.delete", e);
		}
		return redirectToList();
	}

}
