/*
 * Created on 2022-04-12 ( Time 14:44:13 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.vpbank.innovation.bean.DmsDocumentM;
import com.vpbank.innovation.bean.jpa.DmsDocumentMEntity;
import com.vpbank.innovation.bean.jpa.DmsSystemEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class DmsDocumentMServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public DmsDocumentMServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'DmsDocumentMEntity' to 'DmsDocumentM'
	 * @param dmsDocumentMEntity
	 */
	public DmsDocumentM mapDmsDocumentMEntityToDmsDocumentM(DmsDocumentMEntity dmsDocumentMEntity) {
		if(dmsDocumentMEntity == null) {
			return null;
		}

		//--- Generic mapping 
		DmsDocumentM dmsDocumentM = map(dmsDocumentMEntity, DmsDocumentM.class);

		//--- Link mapping ( link to DmsSystem )
		if(dmsDocumentMEntity.getDmsSystem() != null) {
			dmsDocumentM.setSystemId(dmsDocumentMEntity.getDmsSystem().getId());
		}
		return dmsDocumentM;
	}
	
	/**
	 * Mapping from 'DmsDocumentM' to 'DmsDocumentMEntity'
	 * @param dmsDocumentM
	 * @param dmsDocumentMEntity
	 */
	public void mapDmsDocumentMToDmsDocumentMEntity(DmsDocumentM dmsDocumentM, DmsDocumentMEntity dmsDocumentMEntity) {
		if(dmsDocumentM == null) {
			return;
		}

		//--- Generic mapping 
		map(dmsDocumentM, dmsDocumentMEntity);

		//--- Link mapping ( link : dmsDocumentM )
		if( hasLinkToDmsSystem(dmsDocumentM) ) {
			DmsSystemEntity dmsSystem1 = new DmsSystemEntity();
			dmsSystem1.setId( dmsDocumentM.getSystemId() );
			dmsDocumentMEntity.setDmsSystem( dmsSystem1 );
		} else {
			dmsDocumentMEntity.setDmsSystem( null );
		}

	}
	
	/**
	 * Verify that DmsSystem id is valid.
	 * @param DmsSystem DmsSystem
	 * @return boolean
	 */
	private boolean hasLinkToDmsSystem(DmsDocumentM dmsDocumentM) {
		if(dmsDocumentM.getSystemId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}