/*
 * Created on 2022-04-14 ( Time 09:45:05 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.vpbank.innovation.bean.FvUser;
import com.vpbank.innovation.bean.jpa.FvUserEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class FvUserServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public FvUserServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'FvUserEntity' to 'FvUser'
	 * @param fvUserEntity
	 */
	public FvUser mapFvUserEntityToFvUser(FvUserEntity fvUserEntity) {
		if(fvUserEntity == null) {
			return null;
		}

		//--- Generic mapping 
		FvUser fvUser = map(fvUserEntity, FvUser.class);

		return fvUser;
	}
	
	/**
	 * Mapping from 'FvUser' to 'FvUserEntity'
	 * @param fvUser
	 * @param fvUserEntity
	 */
	public void mapFvUserToFvUserEntity(FvUser fvUser, FvUserEntity fvUserEntity) {
		if(fvUser == null) {
			return;
		}

		//--- Generic mapping 
		map(fvUser, fvUserEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}