/*
 * Created on 2022-04-14 ( Time 15:22:28 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.vpbank.innovation.bean.IapprPinOtp;
import com.vpbank.innovation.bean.jpa.IapprPinOtpEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class IapprPinOtpServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public IapprPinOtpServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'IapprPinOtpEntity' to 'IapprPinOtp'
	 * @param iapprPinOtpEntity
	 */
	public IapprPinOtp mapIapprPinOtpEntityToIapprPinOtp(IapprPinOtpEntity iapprPinOtpEntity) {
		if(iapprPinOtpEntity == null) {
			return null;
		}

		//--- Generic mapping 
		IapprPinOtp iapprPinOtp = map(iapprPinOtpEntity, IapprPinOtp.class);

		return iapprPinOtp;
	}
	
	/**
	 * Mapping from 'IapprPinOtp' to 'IapprPinOtpEntity'
	 * @param iapprPinOtp
	 * @param iapprPinOtpEntity
	 */
	public void mapIapprPinOtpToIapprPinOtpEntity(IapprPinOtp iapprPinOtp, IapprPinOtpEntity iapprPinOtpEntity) {
		if(iapprPinOtp == null) {
			return;
		}

		//--- Generic mapping 
		map(iapprPinOtp, iapprPinOtpEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}