/*
 * Created on 2022-04-14 ( Time 15:22:13 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.vpbank.innovation.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.vpbank.innovation.bean.IapprCodeOtp;
import com.vpbank.innovation.bean.jpa.IapprCodeOtpEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class IapprCodeOtpServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public IapprCodeOtpServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'IapprCodeOtpEntity' to 'IapprCodeOtp'
	 * @param iapprCodeOtpEntity
	 */
	public IapprCodeOtp mapIapprCodeOtpEntityToIapprCodeOtp(IapprCodeOtpEntity iapprCodeOtpEntity) {
		if(iapprCodeOtpEntity == null) {
			return null;
		}

		//--- Generic mapping 
		IapprCodeOtp iapprCodeOtp = map(iapprCodeOtpEntity, IapprCodeOtp.class);

		return iapprCodeOtp;
	}
	
	/**
	 * Mapping from 'IapprCodeOtp' to 'IapprCodeOtpEntity'
	 * @param iapprCodeOtp
	 * @param iapprCodeOtpEntity
	 */
	public void mapIapprCodeOtpToIapprCodeOtpEntity(IapprCodeOtp iapprCodeOtp, IapprCodeOtpEntity iapprCodeOtpEntity) {
		if(iapprCodeOtp == null) {
			return;
		}

		//--- Generic mapping 
		map(iapprCodeOtp, iapprCodeOtpEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}